version: '3'
services:

        # Database for the project
        db:
                # Build database using file in db directory
                build: ./db

                # Set the port to the default port for MYSQL and expose to same host port
                ports:
                        - "3306:3306"

                # Try to restart container if it crashes or stops
                restart: always


        # Admin tools for the above database
        adminer:
                # Use the latest adminer image
                image: adminer

                # Set the host port to 8080 and link it with port 8080 in the container
                ports:
                        - "8080:8080"
                
                # Wait for the database to spin up
                depends_on:
                        - db

                # Try to restart container if it crashes or stops
                restart: always



